name: Test Action

on:
    push:
    workflow_dispatch:

jobs:
    hello:
        runs-on: ubuntu-latest
        # defaults:
        #   run:
        #     working-directory: ./.github/actions/custom-action-js

        steps:
            - uses: actions/checkout@v4

            - name: Abhängigkeiten installieren
              run: npm install
              working-directory: ./.github/actions/custom-action-js

            - name: Action ausführen
              uses: ./.github/actions/custom-action-js
              with:
                name: 'Datev'