# Workflow Konfiguration
name: Hello World

# Events
on: push

# Jobs
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - name: Aktuelles Verzeichnis ansehen
              run: pwd && ls -al

            - name: Checkout der Dateien
              uses: actions/checkout@v4

            - name: Aktuelles Verzeichnis ansehen
              run: pwd && ls -al
            
            - name: Lade hello-world.js als Artifact hoch
              uses: actions/upload-artifact@v4
              with:
                name: hello-world.js datei
                path: hello-world.js

    Bye:
        runs-on: ubuntu-latest
        needs: hello
        steps:
            - name: Lade hello-world.js von Artifact herunter
              uses: actions/download-artifact@v4
              with:
                name: hello-world.js datei

            - name: Aktuelles Verzeichnis ansehen
              run: pwd && ls -al

            - name: Nodejs ausführen
              run: node hello-world.js

            - name: Abschied
              run: echo "Bye bye"