# Workflow Konfiguration
name: Hello World

# Events
on: push

# Jobs
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - name: Aktuelles Verzeichnis ansehen
              run: pwd && ls -al
            - name: Checkout der Dateien
              uses: actions/checkout@v4
            - name: Aktuelles Verzeichnis ansehen
              run: pwd && ls -al
            - name: Nodejs ausführen
              run: node hello-world.js
    Bye:
        runs-on: ubuntu-latest
        needs: hello
        steps:
            - name: Aktuelles Verzeichnis ansehen
              run: pwd && ls -al
            - name: Abschied
              run: echo "Bye bye"